server:
  port: 8082
  compression:
    enabled: true

spring:
  application:
    name: order-server
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
#        httpclient: 
#          hc5:
#            enabled: false

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/

logging:
  level:
#    ROOT: DEBUG
    com.llllxr.client.UserClient: DEBUG
    
