#服务端口，随便起
server:
  port: 8082
#服务名称
spring:
  application:
    name: order-server

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/

logging:
  level:
    ROOT: DEBUG