server:
  port: 8082
  compression:
    enabled: true

spring:
  application:
    name: order-server
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          min-request-size: 1
          mime-types: text/xml,application/xml,application/json
        response:
          enabled: true
          useGzipDecoder: true
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
#        httpclient: 
#          hc5:
#            enabled: false

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/

logging:
  level:
#    ROOT: DEBUG
    com.llllxr.client.UserClient: DEBUG
    
